#!/bin/sh

if [ -d "/usr/lib64" ]; then
	echo "multilib situation!"
	LIBDIR="/usr/lib64"
else
	LIBDIR="/usr/lib"
fi

rm $LIBDIR/enigma2/python/Plugins/Extensions/FanControl/*.pyo > /dev/null 2>&1
rm $LIBDIR/enigma2/python/Plugins/Extensions/WebInterface/WebChilds/External/FC2web.pyo > /dev/null 2>&1
rm $LIBDIR/enigma2/python/Plugins/Extensions/WebInterface/web-data/fc2/diagram.class > /dev/null 2>&1
echo "*                               *"
echo "* E2 restart is required        *"
echo "*                               *"
echo "* E2 muss neu gestartet werden  *"
echo "*                               *"

exit 0
